### ISSUE TITLE
Code license 

### ISSUE THREAD

**Issue by huard** [SantanderMetGroup/R_VALUE#17]
The R_VALUE code is under the GNU General Public License, which is a ShareAlike license. I was wondering if it was possible to release the code under a more permissive license?

**Comment by jbedia** [comment]
Hi David. This package is deprecated and no longer in use. It was superseded some years ago by the package [VALUE](https://github.com/SantanderMetGroup/VALUE), distributed under the GPLv3 license terms.

**Comment by huard** [comment]
Ok thanks ! We'll have the same issue I suppose with VALUE and its copyleft license.
